server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  application:
    name: authorization-server
  datasource: